/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FingerprintRouteImport } from './routes/fingerprint'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as LiveWorkbenchRouteImport } from './routes/live.workbench'
import { Route as LabLapfileRouteImport } from './routes/lab.lapfile'
import { Route as ApiPublicOgShareTokenRouteImport } from './routes/api/public/og/share.$token'

const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintRoute = FingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveWorkbenchRoute = LiveWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => LiveRoute,
} as any)
const LabLapfileRoute = LabLapfileRouteImport.update({
  id: '/lab/lapfile',
  path: '/lab/lapfile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgShareTokenRoute = ApiPublicOgShareTokenRouteImport.update({
  id: '/api/public/og/share/$token',
  path: '/api/public/og/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fingerprint': typeof FingerprintRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRouteWithChildren
  '/lab/lapfile': typeof LabLapfileRoute
  '/live/workbench': typeof LiveWorkbenchRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sessions/': typeof SessionsIndexRoute
  '/api/public/og/share/$token': typeof ApiPublicOgShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fingerprint': typeof FingerprintRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRouteWithChildren
  '/lab/lapfile': typeof LabLapfileRoute
  '/live/workbench': typeof LiveWorkbenchRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sessions': typeof SessionsIndexRoute
  '/api/public/og/share/$token': typeof ApiPublicOgShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fingerprint': typeof FingerprintRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRouteWithChildren
  '/lab/lapfile': typeof LabLapfileRoute
  '/live/workbench': typeof LiveWorkbenchRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sessions/': typeof SessionsIndexRoute
  '/api/public/og/share/$token': typeof ApiPublicOgShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fingerprint'
    | '/how-it-works'
    | '/live'
    | '/lab/lapfile'
    | '/live/workbench'
    | '/sessions/$id'
    | '/share/$token'
    | '/sessions/'
    | '/api/public/og/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fingerprint'
    | '/how-it-works'
    | '/live'
    | '/lab/lapfile'
    | '/live/workbench'
    | '/sessions/$id'
    | '/share/$token'
    | '/sessions'
    | '/api/public/og/share/$token'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/fingerprint'
    | '/how-it-works'
    | '/live'
    | '/lab/lapfile'
    | '/live/workbench'
    | '/sessions/$id'
    | '/share/$token'
    | '/sessions/'
    | '/api/public/og/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FingerprintRoute: typeof FingerprintRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LiveRoute: typeof LiveRouteWithChildren
  LabLapfileRoute: typeof LabLapfileRoute
  SessionsIdRoute: typeof SessionsIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  ApiPublicOgShareTokenRoute: typeof ApiPublicOgShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprint': {
      id: '/fingerprint'
      path: '/fingerprint'
      fullPath: '/fingerprint'
      preLoaderRoute: typeof FingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/workbench': {
      id: '/live/workbench'
      path: '/workbench'
      fullPath: '/live/workbench'
      preLoaderRoute: typeof LiveWorkbenchRouteImport
      parentRoute: typeof LiveRoute
    }
    '/lab/lapfile': {
      id: '/lab/lapfile'
      path: '/lab/lapfile'
      fullPath: '/lab/lapfile'
      preLoaderRoute: typeof LabLapfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/share/$token': {
      id: '/api/public/og/share/$token'
      path: '/api/public/og/share/$token'
      fullPath: '/api/public/og/share/$token'
      preLoaderRoute: typeof ApiPublicOgShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LiveRouteChildren {
  LiveWorkbenchRoute: typeof LiveWorkbenchRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveWorkbenchRoute: LiveWorkbenchRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FingerprintRoute: FingerprintRoute,
  HowItWorksRoute: HowItWorksRoute,
  LiveRoute: LiveRouteWithChildren,
  LabLapfileRoute: LabLapfileRoute,
  SessionsIdRoute: SessionsIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  ApiPublicOgShareTokenRoute: ApiPublicOgShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
